### ISSUE TITLE
Server disconnected when running MCP through webMCP-counter

### ISSUE THREAD

**Issue by SynatKeam** [FPetitprez/webMCP-counter#12]
Dear Author, 

I am using webMCP-counter to estimate immune cell infiltration and stromal cells (endothelial cells and fibroblast). 

I have prepared my gene expression count matrix in text file (kindly see attach). My tissue is from mouse and I have been trying both gene symbole and ENSEMBL_ID. However, everytime I run, the server is always disconnected.

Could you help examine whether this is any thing wrong with my file and why the server is always disconnected. 

Note: it works well with example data data set. 
![Server disconnected](https://user-images.githubusercontent.com/86950372/137634770-0ef0c104-8d55-4ad8-adcd-595d5e8ef25f.JPG)
 
![Text file](https://user-images.githubusercontent.com/86950372/137634777-df5c7876-a5e2-478b-bfb1-e287ace25178.JPG)
![text file (ENSEMBL_ID)](https://user-images.githubusercontent.com/86950372/137634797-a1c2c25a-199d-4f73-a748-322465344ef5.JPG)

**Comment by FPetitprez** [comment]
Good to know! Happy to help.
If you use the output of webMCP-counter in a publication on mouse data, please consider citing the mMCP-counter article (doi.org/10.1186/s13073-020-00783-w) and the webMCP-counter preprint (doi.org/10.1101/2020.12.03.400754). Thank you!

Best regards,

Florent
