### ISSUE TITLE
MCP-counter gene symbols

### ISSUE THREAD

**Issue by sdcanli** [FPetitprez/webMCP-counter#13]
Hi,

I am planning to run MCP-counter for a dataset. I generated the input file with gene symbols in the first column as requested. The dataset is in Illumina platform, and I guess MCP-counter is not designed to work with Illumina arrays at the probe level, therefore I generated the file using gene symbols. Since there are multiple probesets for some genes, I have more then one row for some genes as in the image below.
![image](https://user-images.githubusercontent.com/79647287/140326429-6a54575f-c06b-4bc4-b56a-0e8c7be6b400.png)

My question is whether I should have only one row for each gene? Should I choose one based on average, varitation etc.

My second question is whether the normalization method matter for the MCP-counter to run and generate reliable results? 

Thanks in advence

**Comment by FPetitprez** [comment]
Hello, and thank you for reaching out.

1) webMCP-counter only reads the first occurrence of each gene. This is a behavior that we plan to modify in the future, but for now, the other occurrences of each gene will be ignored. I would suggest to aggregate data by computing the average expression value for each gene.
2) Regarding normalization, the MCP-counter scores will be expressed in the same type of values as the genes expression you input. To have something that allows comparison between samples, you need a normalization method that allows to compare gene expression as well. My usual suggestion is to TPM, and use data in logarithm values, i.e. log2(1+TPM).

I hope this helps!

Best wishes,
Florent

**Comment by sdcanli** [comment]
Hi ,

Thanks a lot for your quick response Florent.   I will then calculate average for multiple occurences while using microarray data.

Best regards and thanks for this clear answer

**Comment by FPetitprez** [comment]
No problem, hope webMCP-counter is useful! If you use output from webMCP-counter in a publication, could you please consider citing the original MCP-counter article (in your case the human version https://doi.org/10.1186/s13059-016-1070-5) as well as the preprint for the web app (https://biorxiv.org/cgi/content/short/2020.12.03.400754v1). Thank you in advance.
Best regards,
Florent
