### ISSUE TITLE
Error: Disconnected from the server. Reload

### ISSUE THREAD

**Issue by SevtapYasinoglu** [FPetitprez/webMCP-counter#15]
**Ask your question**
Ask you question as precisely as possible. If this is related to your dataset, do not forget to include key information about it.

Dear Florent,

Thank you for giving me the opportunity to ask for help! I have seen the very interesting preprint of your article on MCP-counter and I wanted to use the web interface to see how it works. But unfortunately, I'm not able to run it. After uploading my excel or txt file, when I click on run, it gives the following error message: Disconnected from the server.
 [Reload](http://134.157.229.105:3838/webMCP/#) I'm not able to continue with the second step. I tried both chrome and edge. 

What could be the reason for this? It would be great if you could help me out. Many thanks in advance. 

Regards,
Sevtap Yasinoglu

**Comment by SevtapYasinoglu** [comment]
Is it perhaps possible to send me an example of the input data?

**Comment by FPetitprez** [comment]
Hi Sevtap,
Thanks for your interest in our work and for reaching out.
webMCP-counter is currently undergoing maintenance. I'll let you know as soon as it is fixed. In the meantime, if you know how to use R, I encourage you to use the R packages [mMCPcounter](https://github.com/cit-bioinfo/mMCP-counter) for mouse data or [MCPcounter](https://github.com/ebecht/MCPcounter) for human data. Sorry for the incovenience, I think it could be fixed in the next days or a couple of weeks.
Regards,
Florent

**Comment by SevtapYasinoglu** [comment]
Dear Florent,

Thank you for your reply. I also tried the R package, but I haven't been successful yet. Since we have to use normalized data expressed in log scale, is it also possible to use differential gene expression data? Column 1 with genes and column 2 with Log2FC? Or what exactly do you use as input? I couldn't find examples. I would prefer to use FPKM values of the samples per group, but I guess that is not possible? 

Best,
Sevtap

**Comment by FPetitprez** [comment]
You need to input the gene expression profiles of all samples, not data aggregated by group. you should have your genes in lines and samples in columns. I usually use log2(1+TPM), but log2(1+FPKM) should be fine as well (but per sample, not per group). First, you need to read your data in R as a data frame or a matrix (if your data is in Excel format, you can use the readr package for instance). Then, you need to call the MCPcounter.estimate() function on this matrix.  You should obtain a table with cell types in lines and samples in columns. Then you can perform comparisons between groups. I hope this helps!

**Comment by SevtapYasinoglu** [comment]
Hi Florent, 

I managed to complete step 1 in R with a lot of help from my colleagues. I am not an experienced R user.. so I have no idea how to continue now in R with the table I have got. Is there a way to find that out? I tried to find the code, but I only found the code of the web tool. Any help would be appreciated. 

Best,
Sevtap

**Comment by FPetitprez** [comment]
If you haven't installed them, you need first to install the MCPcounter of mMCPcounter package (depending on whether you work with human or mouse data)
Link for MCPcouter: https://github.com/ebecht/MCPcounter
Link for mMCPcounter: https://github.com/cit-bioinfo/mMCP-counter

Once you have your dataset loaded in R, if your genes are in row names, you can run the following line:

`MCPcounter::MCPcounter.estimate(yourTable,featuresType="HUGO_symbols")`

where yourTable should be replaced by the name of your table in R. Note that if you are working with mouse data, the line should be:

`mMCPcounter::mMCPcounter.estimate(yourTable)`

These lines are valid if your gene IDs are the gene symbols (e.g. CD8A). If you have them in the ENSEMBL gene format, you need to set the featuresType parameter of MCPcounter.estimate (or the features parameter of mMCPcounter.estimate) to "ENSEMBL.ID".

This will run MCP-counter on your data and return the table of estimates.

**Comment by SevtapYasinoglu** [comment]
Sorry, with the table I meant the estimation table of the cell types in my dataset. Which packages do you recommend for visualization?

**Comment by SevtapYasinoglu** [comment]
Perfect, then I guess I switch to Prism! Thank you!!

**Comment by FPetitprez** [comment]
Glad to have helped! If you use MCP-counter or MCP-counter in a publication, please consider citing the corresponding article: Becht et al, Genome Biology 2016 (for human data) or Petitprez et al, Genome medicine 2020 (for mouse data). Thanks!
