### ISSUE TITLE
Disconnected from the server

### ISSUE THREAD

**Issue by lilichennehcilil** [FPetitprez/webMCP-counter#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here. Notably, if the bug occurred after you loaded your dataset, please describe it briefly here (file format, number of cases, gene ID format, sample ID format).

**Comment by FPetitprez** [comment]
Issue solved by email exchange
