### ISSUE TITLE
run the MCP-counter in special subtype?

### ISSUE THREAD

**Issue by yaphetzk** [FPetitprez/webMCP-counter#7]
**Ask your question**
Ask you question as precisely as possible. If this is related to your dataset, do not forget to include key information about it.

thanks a lot for your wonderful webMCP-counter! However, We wonder if we could run MCP-counter using matrix that is already defined in special subtype ? And the final heatmap could be shown accoding to the defined subtype ?

**Comment by FPetitprez** [comment]
Hello yaphetzk,
Thanks for your interest in webMCP-counter.
What do you mean by special subtype? Do you mean a subtype of immune cell or subtypes of samples?

**Comment by yaphetzk** [comment]
Thank you for your marvelous work in webMCP-counter. Our problem was solved after discussion.




















At 2021-04-13 16:33:50, "FPetitprez" ***@***.***> wrote:

Hello yaphetzk,
Thanks for your interest in webMCP-counter.
What do you mean by special subtype? Do you mean a subtype of immune cell or subtypes of samples?

**Comment by FPetitprez** [comment]
Great to know. If you need more help, don't hesitate to contact me again.
Best regards,
Florent
