### ISSUE TITLE
Disconnected from the server. Reload

### ISSUE THREAD

**Issue by CRubioCiemat** [FPetitprez/webMCP-counter#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here. Notably, if the bug occurred after you loaded your dataset, please describe it briefly here (file format, number of cases, gene ID format, sample ID format).

**Comment by FPetitprez** [comment]
Hello, and thank you for usingg webMCP-counter.
To help me identify the possible error, could you indicate me the following details:
1) OS and web browser you are working on (Windows/Mac/Linux and Firefox/Chrome/...)

2) How is your gene expression data formatted (text file, excel speadsheet)

3) What is the format of the gene IDs (Gene symbol, ENSEMBL)? If you don't know, give me examples of genes from your dataset I can deduce it from this.

4) Are you trying to run it on mouse or human data?

5) Are the samples in columns and the genes in rows? Is the first column of the file the gene IDs?

6) Can you tell me the steps you followed that lead to this error?

**Comment by CRubioCiemat** [comment]
Sorry, I HAVE NOT GIVEN DETAILS.
> Hello, and thank you for using webMCP-counter.
> To help me identify the possible error, could you indicate me the following details:
> 
> 1. OS and web browser you are working on (Windows/Mac/Linux and Firefox/Chrome/...)--> **Windows**
> 2. How is your gene expression data formatted (text file, excel speadsheet)--> **text file**
> 3. What is the format of the gene IDs (Gene symbol, ENSEMBL)? If you don't know, give me examples of genes from your dataset I can deduce it from this. **-->Gene Symbol**
> 4. Are you trying to run it on mouse or human data? --> **in mouse**
> 5. Are the samples in columns and the genes in rows?-->**The samples are in columns and genes in rows** Is the first column of the file the gene IDs?--> **The first column are Gene Symbol**
> 6. Can you tell me the steps you followed that lead to this error?
**I upload the  gene expression profiles file,  I selected the txt format, gene symbol and mouse, and I clic Run**

**Comment by FPetitprez** [comment]
What is the separator used in your file? Do you mind emailing me an example of your data to florent.petitprez@ed.ac.uk ?

**Comment by FPetitprez** [comment]
Hi again. In the sample you gave me, there are 2 things that cause errors:
1. There were many empty lines at the end of your file. There must be no empty line.
2. There was no gene from the mMCP-counter signatures. You need at least one gene of a signature to be present in your data, otherwise it cannot be estimated. If no signature at all can be estimated, this gives an error. The signatures can be found in table S1 of the mMCP-counter article: https://link.springer.com/article/10.1186/s13073-020-00783-w#additional-information

**Comment by FPetitprez** [comment]
What technology was your data generated with? RNA-seq?

**Comment by CRubioCiemat** [comment]
Hello,

Sorry for not answering before. I can check empty lines. My data was generated by Transcriptome Array 1.0 Clarion Mouse. I can't review it right now, but as soon as I do I try again.

Thank’s!
c

De: FPetitprez ***@***.***
Enviado el: viernes, 23 de abril de 2021 16:36
Para: FPetitprez/webMCP-counter ***@***.***>
CC: Rubio Martin, Carolina ***@***.***>; Author ***@***.***>
Asunto: Re: [FPetitprez/webMCP-counter] Disconnected from the server. Reload (#8)


What technology was your data generated with? RNA-seq?
